version: '3'
services:

  xfind47-mysql:
    container_name: 'xfind47.db.mysql'
    platform: linux/amd64
    image: mysql:8.4
    #ports:
    #  - '13006:3306'
    networks:
      - xfind47-dev-network
    environment:
      MYSQL_DATABASE: xfind47-dev-db
      MYSQL_USER: etdev
      MYSQL_PASSWORD: etdev5pass
      MYSQL_ROOT_PASSWORD: rootTwsDev3
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./db/data:/var/lib/mysql

  xfind47-myadmin:
    container_name: 'xfind47.myadmin'
    depends_on:
      - xfind47-mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: xfind47-mysql
    restart: always
    ports:
      - "1001:80"
    networks:
      - xfind47-dev-network

networks:
  xfind47-dev-network:
    driver: bridge
    external: true
    